### ISSUE TITLE
DDL tasks are not described.

### ISSUE THREAD

**Issue by bunnanna** [CleverseAcademy/sql-exercise#4]
In DDL's doc, there are not any description for each step of test case on [Medical appointment](https://github.com/CleverseAcademy/sql-exercise/tree/main/docs/ddl#medical-appointment) and [Organization](https://github.com/CleverseAcademy/sql-exercise/tree/main/docs/ddl#organization).

The tests cannot be passed without information.

So pls update the task description such as initial table schema and what to do with ALTER to [DDL](https://github.com/CleverseAcademy/sql-exercise/tree/main/docs/ddl)

**Comment by intaniger** [comment]
Roger that, the bugfix ETA is October 29th.

**Comment by intaniger** [comment]
@bunnanna please help review #5 to see if any grammar errors or ambiguous sentences.
